services:
  - type: web
    name: novashop-api
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.18.0
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: INTERNAL_WEBHOOK_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
